### PR TITLE
go-delve: coredump implemented for aarch64

### PR DESCRIPTION
**Pull request by ossdev07**
Added support for coredump on ARM64.
Now we can check coredump of ARM64 core files using command "dlv core <executable> <core>"
Floating point registers are not handled yet. 
Please review.

### CODE REVIEW

**Comment by hengwu0** [comment]
Sorry, late to see. But I don't think go-delve will accept this patch actually, becasue they want coredump not arch independent!

**Comment by ossdev07** [comment]
> Sorry, late to see. But I don't think go-delve will accept this patch actually, becasue they want coredump not arch independent!

i am not clear , will you please elaborate what do you mean by "they want coredump not arch independent! "

**Comment by hengwu0** [comment]
> > Sorry, late to see. But I don't think go-delve will accept this patch actually, becasue they want coredump not arch independent!
> 
> i am not clear , will you please elaborate what do you mean by "they want coredump not arch independent! "

They want use dlv_arm64 can open amd64-coredump file, and use dlv_amd64 to open arm64-coredump file too. To simply this means one dlv can parse both amd64-coredump and arm64-coredump file. That arch unindependent.

**Comment by ossdev07** [comment]
> > > Sorry, late to see. But I don't think go-delve will accept this patch actually, becasue they want coredump not arch independent!
> > 
> > 
> > i am not clear , will you please elaborate what do you mean by "they want coredump not arch independent! "
> 
> They want use dlv_arm64 can open amd64-coredump file, and use dlv_amd64 to open arm64-coredump file too. To simply this means one dlv can parse both amd64-coredump and arm64-coredump file. That arch unindependent.

is there any communication about this requirement in delve community

**Comment by hengwu0** [comment]
> > > > Sorry, late to see. But I don't think go-delve will accept this patch actually, becasue they want coredump not arch independent!
> > > 
> > > 
> > > i am not clear , will you please elaborate what do you mean by "they want coredump not arch independent! "
> > 
> > 
> > They want use dlv_arm64 can open amd64-coredump file, and use dlv_amd64 to open arm64-coredump file too. To simply this means one dlv can parse both amd64-coredump and arm64-coredump file. That arch unindependent.
> 
> is there any communication about this requirement in delve community

It's community's idea, not mine... The https://github.com/go-delve/delve/pull/1733 is merged now, you can have a try about this on https://github.com/go-delve/delve. And I will keep going on https://github.com/go-delve/delve/issues/1770.

**Comment by hengwu0** [comment]
It is traced in https://github.com/go-delve/delve/pull/1774, can you close this?

**Comment by ossdev07** [comment]
We closed this PR because raised the same PR on master: https://github.com/go-delve/delve/pull/1774

**Pull request closed without merging**
